name: CI/CD for Develop

on:
  push:
    branches: [ main ]

env:
  ENVIRONMENT: 'main'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Checkout the repo
    - name: Checkout source code
      uses: actions/checkout@v2.2.0
      with:
        path: ${{ env.ENVIRONMENT }}
    # Get tag
    - name: 'Get Previous tag'
      id: previoustag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: tuandiep-restaff/Test
        releases-only: true
      
    - name: Some other action
      run: echo "Octokit is at version ${{ steps.previoustag.outputs.tag }}"
      shell: bash
    
    - name: Write file
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ env.ENVIRONMENT}}/Test/src/CurrentCommit.txt
        contents: |
          echo "${{ steps.previoustag.outputs.tag }}"
        write-mode: append
        
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
         path: ${{ env.ENVIRONMENT}}/Test/src/CurrentCommit.txt
    - name: Echo package.json
      run: echo ${{ steps.package.outputs.content }}
